eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5  # Kas 5 sek. atnaujina informaciją
  instance:
    lease-renewal-interval-in-seconds: 5  # Kas 5 sek. siunčia heartbeat
    lease-expiration-duration-in-seconds: 10  # Po 10 sek. pašalina neveikiančius servisus